### ISSUE TITLE
CIRI-vis fails to generate a fasta file

### ISSUE THREAD

**Issue by drwazeem** [Kevinzjy/CIRIquant-cookbook#12]
I analyzed 12 sets of paired end reads with CIRI-full pipeline and tried to run CIRI-vis on each of them. 11 samples worked fine but for the 12th sample, CIRI-vis generates the circRNA plots and list file, but doesn't output the fasta file. In the Terminal, following error is produced:

`Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at sample_MIX_all_easy4.paint(sample_MIX_all_easy4.java:1278)
	at CIRI_vis_test.main(CIRI_vis_test.java:457)`

Command used:
`java -Xmx4096m -jar CIRI-vis_v1.4.jar -i sampleX_merge_circRNA_detail.anno -l sampleX.as_library_length.list -r genome.fa -min 1 -d sampleX/ciri_vis_out -o sampleX`

TL,DR:
**CIRI-vis generates:
PDFs of detected circRNAs
.list file 

CIRI doesn't generate:
list_circle.fa file**

**Comment by Alipe2021** [comment]
I got the same error. The .list file is empty.

**Comment by Kevinzjy** [comment]
Hi @drwazeem , could you try the latest version of CIRI-vis from https://github.com/bioinfo-biols/CIRI-vis ? The executable jar file is located under the `bin` directory.

**Comment by drwazeem** [comment]
@Kevinzjy Again the same problem. Output is given below: 
`Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at sample_MIX_all_easy4.paint(sample_MIX_all_easy4.java:1275)
        at CIRI_vis_test.main(CIRI_vis_test.java:437)`


Another point I wanted to add: CIRI-viz works fine if I use CIRI_AS output (.jav_list; -d yes) for all samples, including this one.

**Comment by Kevinzjy** [comment]
> @Kevinzjy Again the same problem. Output is given below: `Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 at java.util.ArrayList.rangeCheck(ArrayList.java:653) at java.util.ArrayList.get(ArrayList.java:429) at sample_MIX_all_easy4.paint(sample_MIX_all_easy4.java:1275) at CIRI_vis_test.main(CIRI_vis_test.java:437)`
> 
> Another point I wanted to add: CIRI-viz works fine if I use CIRI_AS output (.jav_list; -d yes) for all samples, including this one.

Yes, '-d yes' is required if you run CIRI2/CIRI-AS/CIRI-full manually. You could refer to the section the following section (https://ciri-cookbook.readthedocs.io/en/latest/CIRI-full.html#how-to-run-the-test-data-set-using-ciri-full) for the full commands.

**Comment by drwazeem** [comment]
Yep that works well without any problems. 
 I am facing problems with just one sample when using the below command:

`java -Xmx4096m -jar CIRI-vis_v1.4.jar -i sampleX_merge_circRNA_detail.anno -l sampleX.as_library_length.list -r genome.fa -min 1 -d sampleX/ciri_vis_out -o sampleX
`
Or 

`java -Xmx4096m -jar CIRI-vis_v1.4.1.jar -i sampleX_merge_circRNA_detail.anno -l sampleX.as_library_length.list -r genome.fa -min 1 -d sampleX/ciri_vis_out -o sampleX
`

**Comment by Kevinzjy** [comment]
Hi @drwazeem @Alipe2021 , we've updated a fixed commit at bioinfo-biols/CIRI-vis@be5dfd0, could you please try it again?

**Comment by drwazeem** [comment]
@Kevinzjy I have tried both. This thread strarted with CIRI-vis_v1.4.jar, but as I said there is the same issue with [CIRI-vis_v1.4.1.jar](https://github.com/bioinfo-biols/CIRI-cookbook/issues/12#issuecomment-976225205). 

Both of them work well when CIRI_as output is used; but both of them fail to generate the fasta file to process one of my 12 samples when I directly use CIRI-full (merge_circRNA_detail.anno) output.

**Comment by Alipe2021** [comment]
Consistent with previous problem,
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:459)
        at sample_MIX_all_easy4.paint(sample_MIX_all_easy4.java:1275)
        at CIRI_vis_test.main(CIRI_vis_test.java:431)
```
