### ISSUE TITLE
Java error when running CIRI_Full_v2.1.1.jar Pipeline 

### ISSUE THREAD

**Issue by smarhon** [Kevinzjy/CIRIquant-cookbook#14]
I get this error message when I run CIRI_Full_v2.1.1.jar Pipeline . 

Exception in thread "main" java.io.FileNotFoundException: RNASeq_LacZAZA_D5_2_CIRI/CIRI-AS_output/RNASeq_LacZAZA_D5_2_CIRI_jav.list (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at Merge3.getmerge(Merge3.java:114)
	at CIRI_Full2.main(CIRI_Full2.java:280)

I checked CIRI-AS_output folder and not files are generated there.

**Comment by Kevinzjy** [comment]
Hi @smarhon , could you check the CIRI_output directory? Is the `.ciri` file successfully generated?
