### ISSUE TITLE
 java -jar CIRI_Full_v2.1.1.jar Merge 

### ISSUE THREAD

**Issue by Thananonsr** [Kevinzjy/CIRIquant-cookbook#36]
Hello everyone,
I’ve been analyzing circRNAs data from RNA sequencing using CIRI2 tools, with a total of 18 samples (running one sample at a time). 
The issue I’m encountering now is when I run the following command: 
**java -jar CIRI_Full_v2.1.1.jar Merge \
-c SRR19666460/rawdata/SRR19666460.ciri \
-as SRR19666460/rawdata/SRR19666460_jav.list \
-ro SRR19666460/rawdata/SRR19666460_ro2_info.list \
-a gencode.v46.annotation.gtf \
-r bwa.index_hg38.fa/hg38.fa \
-o SRR19666460/rawdata \**
unset DISPLAY
classpath = /
Output prefix = /workshop/SRR19666460/rawdata

Merge module start

Loading Annotation...
Annotation Loaded
Loading CIRI_AS output...
CIRI_AS output Loaded
Loading CIRI output...
CIRI output Loaded
Loading CIRI_RO output...
CIRI_RO output Loaded
Combine AS and RO output
Combine completed, 7 reads are used
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.gtflist" is null
        at Exon_gtf.get_exon(Exon_gtf.java:16)
        at Merge3.getmerge(Merge3.java:789)
        at CIRI_Full2.main(CIRI_Full2.java:555)

I’m getting the error message:
**Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.gtflist" is null
    at Exon_gtf.get_exon(Exon_gtf.java:16)
    at Merge3.getmerge(Merge3.java:789)
    at CIRI_Full2.main(CIRI_Full2.java:555)**
This is preventing me from continuing with my analysis. The issue only occurs with one of the samples. Despite my efforts to troubleshoot, I haven’t been able to resolve it. I would appreciate any help from you all.

**Comment by kizliupei** [comment]
Hi, I just met the same issues like:

<img width="519" height="82" alt="Image" src="https://github.com/user-attachments/assets/9c9ed448-569c-40ee-bf16-8d0bf9184e75" />

and I am sure that I got every files need in Merge module, like:

<img width="344" height="550" alt="Image" src="https://github.com/user-attachments/assets/9fca4002-3073-428d-b69c-4e4d1ff6756f" />

when I separately run Merge module as following commands:

ciri_full=~/biosoft/ciri2/CIRI-full_v2.0/CIRI-full.jar
index=~/bioindex/bwa_for_ciri2/mmu_ensembl/mmu.fa
gtf=~/bioannotation/mmu_ensembl/mmu.gtf
ciri=~/bioproject/mypath/03.ciri2/01.CIRI_full/NC_out/CIRI_output/NC.ciri
javlist=~/bioproject/mypath/03.ciri2/01.CIRI_full/NC_out/CIRI-AS_output/NC_jav.list
roinfo=~/bioproject/mypath/03.ciri2/01.CIRI_full/NC_out/CIRI-full_output/NC_ro2_info.list
output=~/bioproject/mypath/03.ciri2/01.CIRI_full
java -jar $ciri_full Merge -a $gtf -c $ciri -as $javlist -ro $roinfo -o $output/testmerge_NC -r $index

I got the same issues like:

<img width="518" height="83" alt="Image" src="https://github.com/user-attachments/assets/e0c8a856-22ea-418b-92f2-2f3e0f1ff177" />

Also, this issue only occurs with one of my samples, any help please?
